<?php

/**
 * This class is the "Area" CMS widget definition
 *
 * @package     Nails
 * @subpackage  module-cms
 * @category    Widget
 * @author      Nails Dev Team
 */

namespace Nails\Cms\Cms\Widget;

use Nails\Cms\Constants;
use Nails\Cms\Widget\WidgetBase;
use Nails\Factory;

/**
 * Class Area
 *
 * @package Nails\Cms\Cms\Widget
 */
class Area extends WidgetBase
{
    /**
     * Area constructor.
     */
    public function __construct()
    {
        parent::__construct();

        $this->label       = 'CMS Area';
        $this->icon        = 'fa-layer-group';
        $this->description = 'Renders the contents of a CMS Area';
        $this->keywords    = 'cms,area,widgets';
    }

    // --------------------------------------------------------------------------

    /**
     * @inheritDoc
     */
    protected function populateWidgetData(array &$aWidgetData)
    {
        $aWidgetData['iAreaId'] = (int) getFromArray('iAreaId', $aWidgetData) ?: null;
        parent::populateWidgetData($aWidgetData);
    }

    // --------------------------------------------------------------------------

    /**
     * @inheritDoc
     */
    public function getEditor(array $aWidgetData = [])
    {
        /** @var \Nails\Cms\Model\Area $oModel */
        $oModel                = Factory::model('Area', Constants::MODULE_SLUG);
        $aWidgetData['aAreas'] = $oModel->getAllFlat();

        return parent::getEditor($aWidgetData); // TODO: Change the autogenerated stub
    }
}
